version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_server_prectice_book_store
    volumes:
      - postgres-data-prectice:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      - web-services

networks:
  web-services:
    driver: bridge

volumes:
  postgres-data-prectice: